title: Medical Guide
description: Wee Dave
theme: just-the-docs

url: https://weedave-development.github.io/daveswebsite

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/weedave-development/daveswebsite
